# dev测试环境部署
name: build dev # workflow名
on:
  push:
    branches:
      - dev
jobs: # 各个作业
  Dockerize:
    runs-on: ubuntu-latest # 运行环境
    steps: # 作业的各个步骤
      - uses: actions/checkout@v2 # git pull
      - name: Login Docker
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build Docker
        run: |
          docker build --platform linux/amd64 --build-arg BUILD_ENV="development" -t lucky-frontend:dev  .
          docker tag lucky-frontend:dev ${{ secrets.DOCKER_REPOSITORY }}
      - name: Push Docker
        run: docker push ${{ secrets.DOCKER_REPOSITORY }}
